# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratio',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
