# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-17 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0006_auto_20190515_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ratio',
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forkilla.Restaurant'),
        ),
    ]
