# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-04 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0011_auto_20190529_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ratio',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='-', max_length=1),
        ),
    ]
